import Providers from "@/components/providers/Providers";
import { Geist, Geist_Mono, Righteous } from "next/font/google";
import { Toaster } from "@/components/ui/sonner";
import ModalRoot from "@/components/common/modals/ModalRoot";
import type { Metadata } from "next";
import "./globals.css";

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });
const righteous = Righteous({ variable: "--font-righteous", weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Truve",
  description: "Generated by create next app",
  icons: {
    icon: "/logo.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/gh/orioncactus/pretendard@v1.3.9/dist/web/static/pretendard.min.css"
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${righteous.variable} antialiased`}
        style={{ fontFamily: "Pretendard, sans-serif" }}
      >
        <Providers>
          {children}
          <Toaster />
          <ModalRoot />
        </Providers>
      </body>
    </html>
  );
}